### ISSUE TITLE
Hello 0xJonaseb11

### ISSUE THREAD

**Issue by spotlight301** [0xJonaseb11/stone.proof.3.0#3]
Hello.
This is Emile Brown , a AI & blockchain developer with 7 years  of experience.
My experience includes developing implementing AI to platforms with including some experience of developing some blockchain platforms.
I think you can make the platform more greatly by implementing the AI technology.

If you don't mind , I 'd like to contribute to the project.
Let's discuss about it.

email : brown22346135@gmail.com
Telegram : @emile0brown

**Comment by 0xJonaseb11** [comment]
Let's discuss about this further!! 
 I love contributions so much!!

**Comment by spotlight301** [comment]
I have already sent you a message by email.
Let's discuss it by email.

**Comment by 0xJonaseb11** [comment]
Sure! Let's loot at it!!
